with 

source as (

    select * from {{ source('projet_lewagon', 'pres2012') }}

),

renamed as (

    select
        CONCAT('FR-',dep) AS code_departement,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixarthaud,
        voixpoutou,
        voixmelenchon,
        voixjoly,
        voixhollande,
        voixcheminade,
        voixbayrou,
        voixsarkozy,
        voixdupontaignan,
        voixmlepen,
        voixt2hollande,
        voixt2sarkozy,
        pvoixarthaud,
        pvoixpoutou,
        pvoixmelenchon,
        pvoixjoly,
        pvoixhollande,
        pvoixcheminade,
        pvoixbayrou,
        pvoixsarkozy,
        pvoixdupontaignan,
        pvoixmlepen,
        pvoixarthaudratio,
        pvoixpoutouratio,
        pvoixmelenchonratio,
        pvoixjolyratio,
        pvoixhollanderatio,
        pvoixcheminaderatio,
        pvoixbayrouratio,
        pvoixsarkozyratio,
        pvoixdupontaignanratio,
        pvoixmlepenratio,
        pvoixt2hollande,
        pvoixt2hollanderatio,
        pvoixt2sarkozy,
        pvoixt2sarkozyratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        pvoteg,
        pvotecg,
        pvotec,
        pvotecd,
        pvoted,
        pvotetg,
        pvotetd,
        pvotegcg,
        pvotedcd,
        pvotegratio,
        pvotecgratio,
        pvotecratio,
        pvotecdratio,
        pvotedratio,
        pvotegcgratio,
        pvotedcdratio,
        pvotetgratio,
        pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        paris,
        nomcanton,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
