with 

source as (

    select * from {{ source('projet_lewagon', 'pres2012') }}

),

renamed as (

    select
        dep,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixarthaud,
        voixpoutou,
        voixmelenchon,
        voixjoly,
        voixhollande,
        voixcheminade,
        voixbayrou,
        voixsarkozy,
        voixdupontaignan,
        voixmlepen,
        voixt2hollande,
        voixt2sarkozy,
        COALESCE(SAFE_CAST(pvoixarthaud AS FLOAT64), 0) AS pvoixarthaud,
        COALESCE(SAFE_CAST(pvoixpoutou AS FLOAT64), 0) AS pvoixpoutou,
        COALESCE(SAFE_CAST(pvoixmelenchon AS FLOAT64), 0) AS pvoixmelenchon,
        COALESCE(SAFE_CAST(pvoixjoly AS FLOAT64), 0) AS pvoixjoly,
        COALESCE(SAFE_CAST(pvoixhollande AS FLOAT64), 0) AS pvoixhollande,
        COALESCE(SAFE_CAST(pvoixcheminade AS FLOAT64), 0) AS pvoixcheminade,
        COALESCE(SAFE_CAST(pvoixbayrou AS FLOAT64), 0) AS pvoixbayrou,
        COALESCE(SAFE_CAST(pvoixsarkozy AS FLOAT64), 0) AS pvoixsarkozy,
        COALESCE(SAFE_CAST(pvoixdupontaignan AS FLOAT64), 0) AS pvoixdupontaignan,
        COALESCE(SAFE_CAST(pvoixmlepen AS FLOAT64), 0) AS pvoixmlepen,
        COALESCE(SAFE_CAST(pvoixarthaudratio AS FLOAT64), 0) AS pvoixarthaudratio,
        COALESCE(SAFE_CAST(pvoixpoutouratio AS FLOAT64), 0) AS pvoixpoutouratio,
        COALESCE(SAFE_CAST(pvoixmelenchonratio AS FLOAT64), 0) AS pvoixmelenchonratio,
        COALESCE(SAFE_CAST(pvoixjolyratio AS FLOAT64), 0) AS pvoixjolyratio,
        COALESCE(SAFE_CAST(pvoixhollanderatio AS FLOAT64), 0) AS pvoixhollanderatio,
        COALESCE(SAFE_CAST(pvoixcheminaderatio AS FLOAT64), 0) AS pvoixcheminaderatio,
        COALESCE(SAFE_CAST(pvoixbayrouratio AS FLOAT64), 0) AS pvoixbayrouratio,
        COALESCE(SAFE_CAST(pvoixsarkozyratio AS FLOAT64), 0) AS pvoixsarkozyratio,
        COALESCE(SAFE_CAST(pvoixdupontaignanratio AS FLOAT64), 0) AS pvoixdupontaignanratio,
        COALESCE(SAFE_CAST(pvoixmlepenratio AS FLOAT64), 0) AS pvoixmlepenratio,
        pvoixt2hollande,
        pvoixt2hollanderatio,
        pvoixt2sarkozy,
        pvoixt2sarkozyratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        COALESCE(SAFE_CAST(pvoteg AS FLOAT64), 0) AS pvoteg,
        COALESCE(SAFE_CAST(pvotecg AS FLOAT64), 0) AS pvotecg,
        COALESCE(SAFE_CAST(pvotec AS FLOAT64), 0) AS pvotec,
        COALESCE(SAFE_CAST(pvotecd AS FLOAT64), 0) AS pvotecd,
        COALESCE(SAFE_CAST(pvoted AS FLOAT64), 0) AS pvoted,
        COALESCE(SAFE_CAST(pvotetg AS FLOAT64), 0) AS pvotetg,
        COALESCE(SAFE_CAST(pvotetd AS FLOAT64), 0) AS pvotetd,
        COALESCE(SAFE_CAST(pvotegcg AS FLOAT64), 0) AS pvotegcg,
        COALESCE(SAFE_CAST(pvotedcd AS FLOAT64), 0) AS pvotedcd,
        COALESCE(SAFE_CAST(pvotegratio AS FLOAT64), 0) AS pvotegratio,
        COALESCE(SAFE_CAST(pvotecgratio AS FLOAT64), 0) AS pvotecgratio,
        COALESCE(SAFE_CAST(pvotecratio AS FLOAT64), 0) AS pvotecratio,
        COALESCE(SAFE_CAST(pvotecdratio AS FLOAT64), 0) AS pvotecdratio,
        COALESCE(SAFE_CAST(pvotedratio AS FLOAT64), 0) AS pvotedratio,
        COALESCE(SAFE_CAST(pvotegcgratio AS FLOAT64), 0) AS pvotegcgratio,
        COALESCE(SAFE_CAST(pvotedcdratio AS FLOAT64), 0) AS pvotedcdratio,
        COALESCE(SAFE_CAST(pvotetgratio AS FLOAT64), 0) AS pvotetgratio,
        COALESCE(SAFE_CAST(pvotetdratio AS FLOAT64), 0) AS pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        paris,
        nomcanton,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
