with 

source as (

    select * from {{ source('projet_lewagon', 'pres2022') }}

),

renamed as (

    select
        CONCAT('FR-',dep) AS code_departement,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixarthaud,
        voixpoutou,
        voixroussel,
        voixmelenchon,
        voixjadot,
        voixhidalgo,
        voixlassalle,
        voixmacron,
        voixpecresse,
        voixzemmour,
        voixdupontaignan,
        voixmlepen,
        voixt2macron,
        voixt2mlepen,
        pvoixarthaud,
        pvoixpoutou,
        pvoixroussel,
        pvoixmelenchon,
        pvoixjadot,
        pvoixhidalgo,
        pvoixlassalle,
        pvoixmacron,
        pvoixpecresse,
        pvoixzemmour,
        pvoixdupontaignan,
        pvoixmlepen,
        pvoixarthaudratio,
        pvoixpoutouratio,
        pvoixrousselratio,
        pvoixmelenchonratio,
        pvoixjadotratio,
        pvoixhidalgoratio,
        pvoixlassalleratio,
        pvoixmacronratio,
        pvoixpecresseratio,
        pvoixzemmourratio,
        pvoixdupontaignanratio,
        pvoixmlepenratio,
        pvoixt2macron,
        pvoixt2macronratio,
        pvoixt2mlepen,
        pvoixt2mlepenratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        pvoteg,
        pvotecg,
        pvotec,
        pvotecd,
        pvoted,
        pvotetg,
        pvotetd,
        pvotegcg,
        pvotedcd,
        pvotegratio,
        pvotecgratio,
        pvotecratio,
        pvotecdratio,
        pvotedratio,
        pvotegcgratio,
        pvotedcdratio,
        pvotetgratio,
        pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
