with 

source as (

    select * from {{ source('projet_lewagon', 'pres2002') }}

),

renamed as (

    select
        CONCAT('FR-',dep) AS code_departement,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixlaguiller,
        voixbesancenot,
        voixgluckstein,
        voixhue,
        voixtaubira,
        voixmamere,
        voixchevenement,
        voixjospin,
        voixlepage,
        voixsaintjosse,
        voixbayrou,
        voixchirac,
        voixmadelin,
        voixboutin,
        voixmegret,
        voixlepen,
        voixt2chirac,
        voixt2lepen,
        pvoixlaguiller,
        pvoixbesancenot,
        pvoixgluckstein,
        pvoixhue,
        pvoixmamere,
        pvoixtaubira,
        pvoixchevenement,
        pvoixjospin,
        pvoixlepage,
        pvoixsaintjosse,
        pvoixbayrou,
        pvoixchirac,
        pvoixmadelin,
        pvoixboutin,
        pvoixmegret,
        pvoixlepen,
        pvoixlaguillerratio,
        pvoixbesancenotratio,
        pvoixglucksteinratio,
        pvoixhueratio,
        pvoixmamereratio,
        pvoixtaubiraratio,
        pvoixchevenementratio,
        pvoixjospinratio,
        pvoixlepageratio,
        pvoixsaintjosseratio,
        pvoixbayrouratio,
        pvoixchiracratio,
        pvoixmadelinratio,
        pvoixboutinratio,
        pvoixmegretratio,
        pvoixlepenratio,
        pvoixt2chirac,
        pvoixt2chiracratio,
        pvoixt2lepen,
        pvoixt2lepenratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        pvoteg,
        pvotecg,
        pvotec,
        pvotecd,
        pvoted,
        pvotetg,
        pvotetd,
        pvotegcg,
        pvotedcd,
        pvotegratio,
        pvotecgratio,
        pvotecratio,
        pvotecdratio,
        pvotedratio,
        pvotegcgratio,
        pvotedcdratio,
        pvotetgratio,
        pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        paris,
        nomcanton,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
