with 

source as (

    select * from {{ source('projet_lewagon', 'pres2017') }}

),

renamed as (

    select
        dep,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixarthaud,
        voixpoutou,
        voixmelenchon,
        voixhamon,
        voixcheminade,
        voixlassalle,
        voixmacron,
        voixfillon,
        voixasselineau,
        voixdupontaignan,
        voixmlepen,
        voixt2macron,
        voixt2mlepen,
        pvoixarthaud,
        pvoixpoutou,
        pvoixmelenchon,
        pvoixhamon,
        pvoixcheminade,
        pvoixlassalle,
        pvoixmacron,
        pvoixfillon,
        pvoixasselineau,
        pvoixdupontaignan,
        pvoixmlepen,
        pvoixarthaudratio,
        pvoixpoutouratio,
        pvoixmelenchonratio,
        pvoixhamonratio,
        pvoixcheminaderatio,
        pvoixlassalleratio,
        pvoixmacronratio,
        pvoixfillonratio,
        pvoixasselineauratio,
        pvoixdupontaignanratio,
        pvoixmlepenratio,
        pvoixt2macron,
        pvoixt2macronratio,
        pvoixt2mlepen,
        pvoixt2mlepenratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        pvoteg,
        pvotecg,
        pvotec,
        pvotecd,
        pvoted,
        pvotetg,
        pvotetd,
        pvotegcg,
        pvotedcd,
        pvotegratio,
        pvotecgratio,
        pvotecratio,
        pvotecdratio,
        pvotedratio,
        pvotegcgratio,
        pvotedcdratio,
        pvotetgratio,
        pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
