{{ config(
    materialized='table'
) }}

with 

source as (

    select * from {{ source('projet_lewagon', 'pres2007') }}

),

renamed as (

    select
        CONCAT('FR-',dep) AS code_departement,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixlaguiller,
        voixbesancenot,
        voixschivardi,
        voixbuffet,
        voixbove,
        voixvoynet,
        voixroyal,
        voixnihous,
        voixbayrou,
        voixsarkozy,
        voixvilliers,
        voixlepen,
        voixt2royal,
        voixt2sarkozy,
        COALESCE(SAFE_CAST(pvoixlaguiller AS FLOAT64), 0) AS pvoixlaguiller,
        COALESCE(SAFE_CAST(pvoixbesancenot AS FLOAT64), 0) AS pvoixbesancenot,
        COALESCE(SAFE_CAST(pvoixschivardi AS FLOAT64), 0) AS pvoixschivardi,
        COALESCE(SAFE_CAST(pvoixbuffet AS FLOAT64), 0) AS pvoixbuffet,
        COALESCE(SAFE_CAST(pvoixbove AS FLOAT64), 0) AS pvoixbove,
        COALESCE(SAFE_CAST(pvoixvoynet AS FLOAT64), 0) AS pvoixvoynet,
        COALESCE(SAFE_CAST(pvoixroyal AS FLOAT64), 0) AS pvoixroyal,
        COALESCE(SAFE_CAST(pvoixnihous AS FLOAT64), 0) AS pvoixnihous,
        COALESCE(SAFE_CAST(pvoixbayrou AS FLOAT64), 0) AS pvoixbayrou,
        COALESCE(SAFE_CAST(pvoixsarkozy AS FLOAT64), 0) AS pvoixsarkozy,
        COALESCE(SAFE_CAST(pvoixvilliers AS FLOAT64), 0) AS pvoixvilliers,
        COALESCE(SAFE_CAST(pvoixlepen AS FLOAT64), 0) AS pvoixlepen,
        COALESCE(SAFE_CAST(pvoixlaguillerratio AS FLOAT64), 0) AS pvoixlaguillerratio,
        COALESCE(SAFE_CAST(pvoixbesancenotratio AS FLOAT64), 0) AS pvoixbesancenotratio,
        COALESCE(SAFE_CAST(pvoixschivardiratio AS FLOAT64), 0) AS pvoixschivardiratio,
        COALESCE(SAFE_CAST(pvoixbuffetratio AS FLOAT64), 0) AS pvoixbuffetratio,
        COALESCE(SAFE_CAST(pvoixboveratio AS FLOAT64), 0) AS pvoixboveratio,
        COALESCE(SAFE_CAST(pvoixvoynetratio AS FLOAT64), 0) AS pvoixvoynetratio,
        COALESCE(SAFE_CAST(pvoixroyalratio AS FLOAT64), 0) AS pvoixroyalratio,
        COALESCE(SAFE_CAST(pvoixnihousratio AS FLOAT64), 0) AS pvoixnihousratio,
        COALESCE(SAFE_CAST(pvoixbayrouratio AS FLOAT64), 0) AS pvoixbayrouratio,
        COALESCE(SAFE_CAST(pvoixsarkozyratio AS FLOAT64), 0) AS pvoixsarkozyratio,
        COALESCE(SAFE_CAST(pvoixvilliersratio AS FLOAT64), 0) AS pvoixvilliersratio,
        COALESCE(SAFE_CAST(pvoixlepenratio AS FLOAT64), 0) AS pvoixlepenratio,
        pvoixt2royal,
        pvoixt2royalratio,
        pvoixt2sarkozy,
        pvoixt2sarkozyratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        COALESCE(SAFE_CAST(pvoteg AS FLOAT64), 0) AS pvoteg,
        COALESCE(SAFE_CAST(pvotecg AS FLOAT64), 0) AS pvotecg,
        COALESCE(SAFE_CAST(pvotec AS FLOAT64), 0) AS pvotec,
        COALESCE(SAFE_CAST(pvotecd AS FLOAT64), 0) AS pvotecd,
        COALESCE(SAFE_CAST(pvoted AS FLOAT64), 0) AS pvoted,
        COALESCE(SAFE_CAST(pvotetg AS FLOAT64), 0) AS pvotetg,
        COALESCE(SAFE_CAST(pvotetd AS FLOAT64), 0) AS pvotetd,
        COALESCE(SAFE_CAST(pvotegcg AS FLOAT64), 0) AS pvotegcg,
        COALESCE(SAFE_CAST(pvotedcd AS FLOAT64), 0) AS pvotedcd,
        COALESCE(SAFE_CAST(pvotegratio AS FLOAT64), 0) AS pvotegratio,
        COALESCE(SAFE_CAST(pvotecgratio AS FLOAT64), 0) AS pvotecgratio,
        COALESCE(SAFE_CAST(pvotecratio AS FLOAT64), 0) AS pvotecratio,
        COALESCE(SAFE_CAST(pvotecdratio AS FLOAT64), 0) AS pvotecdratio,
        COALESCE(SAFE_CAST(pvotedratio AS FLOAT64), 0) AS pvotedratio,
        COALESCE(SAFE_CAST(pvotegcgratio AS FLOAT64), 0) AS pvotegcgratio,
        COALESCE(SAFE_CAST(pvotedcdratio AS FLOAT64), 0) AS pvotedcdratio,
        COALESCE(SAFE_CAST(pvotetgratio AS FLOAT64), 0) AS pvotetgratio,
        COALESCE(SAFE_CAST(pvotetdratio AS FLOAT64), 0) AS pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        paris,
        nomcanton,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
