with 

source as (

    select * from {{ source('projet_lewagon', 'pres2007') }}

),

renamed as (

    select
        dep,
        nomdep,
        codecommune,
        nomcommune,
        inscrits,
        votants,
        exprimes,
        voixlaguiller,
        voixbesancenot,
        voixschivardi,
        voixbuffet,
        voixbove,
        voixvoynet,
        voixroyal,
        voixnihous,
        voixbayrou,
        voixsarkozy,
        voixvilliers,
        voixlepen,
        voixt2royal,
        voixt2sarkozy,
        pvoixlaguiller,
        pvoixbesancenot,
        pvoixschivardi,
        pvoixbuffet,
        pvoixbove,
        pvoixvoynet,
        pvoixroyal,
        pvoixnihous,
        pvoixbayrou,
        pvoixsarkozy,
        pvoixvilliers,
        pvoixlepen,
        pvoixlaguillerratio,
        pvoixbesancenotratio,
        pvoixschivardiratio,
        pvoixbuffetratio,
        pvoixboveratio,
        pvoixvoynetratio,
        pvoixroyalratio,
        pvoixnihousratio,
        pvoixbayrouratio,
        pvoixsarkozyratio,
        pvoixvilliersratio,
        pvoixlepenratio,
        pvoixt2royal,
        pvoixt2royalratio,
        pvoixt2sarkozy,
        pvoixt2sarkozyratio,
        voteg,
        votecg,
        votec,
        votecd,
        voted,
        votetg,
        votetd,
        votegcg,
        votedcd,
        pvoteg,
        pvotecg,
        pvotec,
        pvotecd,
        pvoted,
        pvotetg,
        pvotetd,
        pvotegcg,
        pvotedcd,
        pvotegratio,
        pvotecgratio,
        pvotecratio,
        pvotecdratio,
        pvotedratio,
        pvotegcgratio,
        pvotedcdratio,
        pvotetgratio,
        pvotetdratio,
        pervoteg,
        pervotecg,
        pervotec,
        pervotecd,
        pervoted,
        pervotegcg,
        pervotedcd,
        pervotetg,
        pervotetd,
        plm,
        plmdoublon,
        ppar,
        perpar,
        pparratio,
        paris,
        nomcanton,
        pabs,
        pblancsnuls,
        inscritst2,
        votantst2,
        exprimest2,
        pabst2,
        pblancsnulst2

    from source

)

select * from renamed
